### PR TITLE
Add web-framework@0.1.1

### PR DESCRIPTION
**Pull request by fraya**

### CODE REVIEW

**Review by cgay — APPROVED** [review]

**Comment by cgay** [comment]
Actually, could you reword the description to "Add web-framework@0.1.1" ?

**Comment by fraya** [comment]
Changed the title

**Comment by cgay** [comment]
> Changed the title

Actually I meant to say the commit description, but don't worry about it. Just a note for future additions.  I'm going to merge this.

**Comment by fraya** [comment]
Sorry, I thought that GH title and PR title were the same :-1:

**Pull request merged**
